import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import SideBar from "./sidebar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function SideBarWrapper({ children }: { children: React.ReactNode }) {
  const cookie = cookies();
  const hasCookies = cookie.get("auth_token_x_clone");
  if (hasCookies) {
    return (
      <div className="flex ">
        <SideBar />
        <div className="w-[60vw]">{children}</div>
        <div className="w-[20vw] border-l-[1px] border-l-slate-700"></div>
      </div>
    );
  }
  return children;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBarWrapper>{children}</SideBarWrapper>
      </body>
    </html>
  );
}
